# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout NEU Repo
        uses: actions/checkout@v4
        with:
          repository: 'NotEnoughUpdates/NotEnoughUpdates-REPO'
          path: 'NotEnoughUpdates-REPO' # This is consistent with the repo path defined in NEURepoParserTest.java
          ref: '080a804a1f7c1fd8e9899f8317a18b33a319d049'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Store test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
